"""Plugin package for Orion Codex."""

from backend.plugins.manager import PluginManager, plugin_manager
from backend.plugins.interfaces import (
    BasePlugin,
    PluginMetadata,
    PluginType,
    AIProviderPlugin,
    BuilderPlugin,
    LanguagePlugin,
    DeploymentPlugin,
    ToolPlugin,
)
from backend.plugins.sdk import (
    PluginDependency,
    PluginManifest,
    PluginMetadata,
    PluginPermission,
    PluginType,
    PluginInstallResult,
    BasePlugin as SDKBasePlugin,
    PluginContext,
    PluginFactory,
    AIProviderPlugin as SDKAIProviderPlugin,
    AgentPlugin,
    ToolPlugin as SDKToolPlugin,
    UIPanelPlugin,
    ThemePlugin,
    DashboardPlugin,
    MemoryProviderPlugin,
    MCPServerPlugin,
    BackgroundServicePlugin,
    ValidatorPlugin,
    HookPlugin,
    EventListenerPlugin,
    CommandPlugin,
    PluginManager as SDKPluginManager,
    plugin_manager as sdk_plugin_manager,
)

__all__ = [
    "PluginManager",
    "plugin_manager",
    "BasePlugin",
    "PluginMetadata",
    "PluginType",
    "AIProviderPlugin",
    "BuilderPlugin",
    "LanguagePlugin",
    "DeploymentPlugin",
    "ToolPlugin",
    "PluginDependency",
    "PluginManifest",
    "PluginMetadata",
    "PluginPermission",
    "PluginInstallResult",
    "SDKBasePlugin",
    "PluginContext",
    "PluginFactory",
    "SDKAIProviderPlugin",
    "AgentPlugin",
    "SDKToolPlugin",
    "UIPanelPlugin",
    "ThemePlugin",
    "DashboardPlugin",
    "MemoryProviderPlugin",
    "MCPServerPlugin",
    "BackgroundServicePlugin",
    "ValidatorPlugin",
    "HookPlugin",
    "EventListenerPlugin",
    "CommandPlugin",
    "SDKPluginManager",
    "sdk_plugin_manager",
]